name: test
on: push
jobs: 
  test:
    name: ${{ matrix.container }}
    strategy:
      matrix:
        container:
          - 'debian:8'
          - 'debian:9'
          - 'debian:10'
          - 'ubuntu:14.04'
          - 'ubuntu:16.04'
          - 'ubuntu:18.04'
          - 'ubuntu:20.04'
          - 'oraclelinux:6'
          - 'oraclelinux:7'
          - 'oraclelinux:8'
          - 'centos:6'
          - 'centos:7'
          - 'centos:8'
          - 'alpine:latest'

      fail-fast: false
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v1
    - name: Install git
      run: |
        yum update || apt-get update || apk update
	yum -y install git || apt-get -y install git || apk add git
        git --version

    - name: Git version
      run: |
        
        git --version

    - name: Install BATS requiremetns
      run: |      
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core && ./install.sh $HOME && cd ..
        git clone https://github.com/ztombol/bats-support
        git clone https://github.com/ztombol/bats-assert

    - name: Run tests
      run: $HOME/bin/bats ./test.bats

